name: SmartTrack
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  supabase_flutter: ^2.3.4
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  pdf: ^3.10.8
  geolocator: ^11.0.0
  table_calendar: ^3.1.0
  app_settings: ^5.1.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  csv: ^5.1.1
  share_plus: ^7.2.2
  device_preview: ^1.1.0
  path_provider: ^2.1.2
  crypto: ^3.0.3
  collection: ^1.18.0
  intl: ^0.20.0
  excel: ^4.0.6 # Added for Excel file parsing
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true